{% set name = "batchstats" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/batchstats-{{ version }}.tar.gz
  sha256: 7400a234a923ba7fc54ca160b0872a0cc2229b9aac758a1bf10cc65cf00351be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - batchstats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Efficient batch statistics computation library for Python.
  home: https://batchstats.readthedocs.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
