{% set name = "batchstats" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/batchstats-{{ version }}.tar.gz
  sha256: 6f8c5d91813342bd182ba36ca7f340e8fe3aea0dc2fb031cea27bbf49bb70c4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - batchstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CyrilJl/BatchStats
  summary: Efficient batch statistics computation library for Python.
  description: Efficiently compute statistics for batch data with batchstats, a Python library optimized for handling streaming inputs and large datasets. batchstats supports a variety of statistical measures, including mean, variance, covariance, sum, min, and max, while ensuring minimal memory usage and high computational speed.  
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
