{% set name = "batchstats" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/batchstats-{{ version }}.tar.gz
  sha256: 477504f4ec1be07b0197d188db91f01068a9ddf5dcfbe3c8562110d374afb25d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - batchstats
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://batchstats.readthedocs.io/en/latest/index.html
  summary: Efficient batch statistics computation library for Python.
  description: Efficiently compute statistics for batch data with batchstats, a Python library optimized for handling streaming inputs and large datasets. batchstats supports a variety of statistical measures, including mean, variance, covariance, sum, min, and max, while ensuring minimal memory usage and high computational speed.  
  dev_url: https://github.com/CyrilJl/BatchStats
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
