{% set name = "batchstats" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/batchstats-{{ version }}.tar.gz
  sha256: a8a22d893178fe4a7b41480ee6bba5b857d5ec30f2a13843d4fb4f4dadd7f952

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - batchstats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Efficient batch statistics computation library for Python.
  home: https://batchstats.readthedocs.io/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
